### ISSUE TITLE
收到，哈哈哈，我邮件作者要代码了，还没要到。然后我重新开了一个问题问一下作者。最后对你说一下抱歉，打扰了，我只是看到你以前问了这个问题，以为你也许复现过这篇论文，所以问一下你。

### ISSUE THREAD

**Issue by More1999** [IBM/Text-to-LogicForm#5]

**Comment by teddylfwu** [comment]
Hi Everyone,

We are working on a big project called Graph4NLP, which we intend to
release at the end of this summer. You will find many many components such
as automatic graph construction that may be useful for your NLP projects.
Please be patient with us and we will give you a big bonus.

Yours sincerely,

Lingfei (Teddy) Wu
Research Staff Member, AI Foundations Labs - Reasoning
IBM Research AI
IBM T. J. Watson Research Center, Yorktown Heights, NY 10598
Phone: +1 757-634-5455
Email: lwu@email.wm.edu, wuli@us.ibm.com
